apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-t104
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-t104
  template:
    metadata:
      labels:
        app: todo-app-t104
    spec:
      containers:
        - name: todo-app-104
          image: tomtom90239/kube-t1.2
